
'use strict';
const td=new TextDecoder();
function readVarint(b,p){let v=0n,s=0n;for(;;){if(p>=b.length)throw Error('truncated varint');let x=b[p++];v|=BigInt(x&127)<<s;if(!(x&128))return [Number(v),p];s+=7n;if(s>70n)throw Error('invalid varint')}}
function* fields(b){let p=0;while(p<b.length){let t;[t,p]=readVarint(b,p);let n=t>>3,w=t&7,v;if(w===0){[v,p]=readVarint(b,p)}else if(w===1){v=b.slice(p,p+8);p+=8}else if(w===2){let z;[z,p]=readVarint(b,p);v=b.slice(p,p+z);p+=z}else if(w===5){v=b.slice(p,p+4);p+=4}else throw Error('unsupported protobuf wire type '+w);yield[n,w,v]}}
const text=b=>td.decode(b); function packedVarints(b){let a=[],p=0,v;while(p<b.length){[v,p]=readVarint(b,p);a.push(v)}return a} function doubles(b){let d=new DataView(b.buffer,b.byteOffset,b.byteLength),a=[];for(let i=0;i<b.length;i+=8)a.push(d.getFloat64(i,true));return a}
function mapEntry(b){let k='',v='';for(let[f,w,x]of fields(b)){if(f===1&&w===2)k=text(x);else if(f===2&&w===2)v=text(x)}return[k,v]}
function node(b){let n={cls:'',method:'',desc:'',line:0,times:[],children:[]};for(let[f,w,x]of fields(b)){if(f===3&&w===2)n.cls=text(x);else if(f===4&&w===2)n.method=text(x);else if(f===6&&w===0)n.line=x;else if(f===7&&w===2)n.desc=text(x);else if(f===8)n.times.push(...(w===2?doubles(x):[new DataView(x.buffer,x.byteOffset,8).getFloat64(0,true)]));else if(f===9)n.children.push(...(w===2?packedVarints(x):[x]))}return n}
function thread(b){let t={name:'',nodes:[],times:[],roots:[]};for(let[f,w,x]of fields(b)){if(f===1&&w===2)t.name=text(x);else if(f===3&&w===2)t.nodes.push(node(x));else if(f===4)t.times.push(...(w===2?doubles(x):[]));else if(f===5)t.roots.push(...(w===2?packedVarints(x):[x]))}return t}
function pluginMeta(b){for(let[f,w,x]of fields(b))if(f===1&&w===2)return text(x);return ''}
function metadata(b,p){for(let[f,w,x]of fields(b)){if(f===2&&w===0)p.start=x;else if(f===3&&w===0)p.interval=x;else if(f===11&&w===0)p.end=x;else if(f===12&&w===0)p.ticks=x;else if(f===15&&w===0)p.mode=x;else if(f===13&&w===2){let key='',name='';for(let[ef,ew,ex]of fields(x)){if(ef===1&&ew===2)key=text(ex);else if(ef===2&&ew===2)name=pluginMeta(ex)}if(key)p.names[key]=name||key}}}
function parse(raw){let p={threads:[],classes:{},methods:{},lines:{},names:{},windows:[],interval:0,start:0,end:0,mode:0,ticks:0};for(let[f,w,x]of fields(raw)){if(f===1&&w===2)metadata(x,p);else if(f===2&&w===2)p.threads.push(thread(x));else if([3,4,5].includes(f)&&w===2){let[k,v]=mapEntry(x);if(k)(f===3?p.classes:f===4?p.methods:p.lines)[k]=v}else if(f===6)p.windows.push(...(w===2?packedVarints(x):[x]))}if(!p.threads.length)throw Error('No Spark SamplerData threads found.');return p}
function source(p,n){let c=[`${n.cls}#${n.method}${n.desc}`,`${n.cls}.${n.method}${n.desc}`,`${n.cls}#${n.method}`,`${n.cls}.${n.method}`];if(n.line)for(let base of c)for(let k of [`${base}:${n.line}`,`${base};${n.line}`])if(k in p.lines)return p.lines[k];for(let k of c)if(k in p.methods)return p.methods[k];return p.classes[n.cls]||null}
const frameworks=new Set(['packetevents','protocollib','viaversion','viabackwards','viarewind']);function isFramework(p,s){return !!s&&frameworks.has((p.names[s]||s).toLowerCase().replaceAll(' ',''))}
function barrier(n){let c=n.cls,m=n.method;if(c.startsWith('io.netty.channel.AbstractChannelHandlerContext'))return m.startsWith('invoke')||['write','fireChannelRead','read','flush','fireChannelReadComplete','fireExceptionCaught'].includes(m);if(c.startsWith('io.netty.channel.DefaultChannelPipeline')||c.startsWith('io.netty.channel.CombinedChannelDuplexHandler'))return true;if(['io.netty.channel.ChannelDuplexHandler','io.netty.channel.ChannelInboundHandlerAdapter','io.netty.channel.ChannelOutboundHandlerAdapter'].includes(c))return ['write','channelRead','read','flush'].includes(m);return false}
const sum=a=>a.reduce((x,y)=>x+y,0);function fmtBytes(n){if(n>=1048576)return(n/1048576).toFixed(2)+' MB';if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B'}function analyze(p,filter){let caused={},totalSelf=0;for(let t of p.threads){if(filter&&!t.name.toLowerCase().includes(filter.toLowerCase()))continue;let ns=t.nodes;function walk(i,active,seen){if(i<0||i>=ns.length||seen.has(i))return;let n=ns[i],inc=sum(n.times),own=source(p,n),inherited=barrier(n)?null:active,current;if(own)current=isFramework(p,own)&&inherited&&!isFramework(p,inherited)?inherited:own;else current=inherited;let cs=0,valid=[];for(let c of n.children)if(c>=0&&c<ns.length){cs+=sum(ns[c].times);valid.push(c)}let self=Math.max(0,inc-cs);totalSelf+=self;if(current)caused[current]=(caused[current]||0)+self;let nv=new Set(seen);nv.add(i);for(let c of valid)walk(c,current,nv)}for(let r of t.roots)walk(r,null,new Set)}return{caused,totalSelf}}
function rate(x){let a=Math.abs(x);if(a>=1024**3)return(x/1024**3).toFixed(3)+' GB/s';if(a>=1024**2)return(x/1024**2).toFixed(2)+' MB/s';if(a>=1024)return(x/1024).toFixed(2)+' KB/s';return x.toFixed(2)+' B/s'}

// --- protobuf-preserving CPU/idle post processor (ported from spark_cpu_filter_v3.py) ---
function encVarint(n){let v=BigInt(Math.max(0,Math.trunc(n))),a=[];do{let x=Number(v&127n);v>>=7n;if(v)x|=128;a.push(x)}while(v);return new Uint8Array(a)}
function concat(parts){let n=parts.reduce((s,x)=>s+x.length,0),o=new Uint8Array(n),p=0;for(let x of parts){o.set(x,p);p+=x.length}return o}
function tag(f,w){return encVarint((f<<3)|w)}
function fieldBytes(f,w,v){if(w===0)return concat([tag(f,w),encVarint(v)]);if(w===1)return concat([tag(f,w),v]);if(w===2)return concat([tag(f,w),encVarint(v.length),v]);if(w===5)return concat([tag(f,w),v]);throw Error('wire')}
function encodeFields(fs){return concat(fs.map(x=>fieldBytes(x.f,x.w,x.v)))}
function rawFields(b){let out=[],p=0;while(p<b.length){let t;[t,p]=readVarint(b,p);let f=t>>3,w=t&7,v;if(w===0){[v,p]=readVarint(b,p)}else if(w===1){v=b.slice(p,p+8);p+=8}else if(w===2){let z;[z,p]=readVarint(b,p);v=b.slice(p,p+z);p+=z}else if(w===5){v=b.slice(p,p+4);p+=4}else throw Error('wire '+w);out.push({f,w,v})}return out}
function packDoubles(a){let b=new Uint8Array(a.length*8),d=new DataView(b.buffer);a.forEach((v,i)=>d.setFloat64(i*8,Math.max(0,v),true));return b}
function getPackedDoubles(fs,num){let a=[];for(let x of fs)if(x.f===num){if(x.w===2)a.push(...doubles(x.v));else if(x.w===1)a.push(new DataView(x.v.buffer,x.v.byteOffset,8).getFloat64(0,true))}return a}
function replacePackedDoubles(fs,num,a){let first=fs.findIndex(x=>x.f===num),clean=fs.filter(x=>x.f!==num);if(!a.length)return clean;let nf={f:num,w:2,v:packDoubles(a)};if(first<0){clean.push(nf);return clean}let before=fs.slice(0,first).filter(x=>x.f!==num),after=fs.slice(first).filter(x=>x.f!==num);return [...before,nf,...after]}
function packVars(a){return concat(a.map(encVarint))}
function sleepingV3(cls,method){
  const c=(cls||'').replaceAll('/','.'), m=(method||''), ml=m.toLowerCase(), cl=c.toLowerCase();
  const exact=new Set(['java.lang.Thread|sleep','java.lang.Object|wait','java.util.concurrent.locks.LockSupport|park','java.util.concurrent.locks.LockSupport|parkNanos','java.util.concurrent.locks.LockSupport|parkUntil','jdk.internal.misc.Unsafe|park','sun.misc.Unsafe|park']);
  if(exact.has(c+'|'+m))return true;
  if(cl.includes('epoll')&&['wait','epollwait','epoll_wait'].includes(ml))return true;
  if(cl.includes('kqueue')&&['wait','kevent','kqueuewait'].includes(ml))return true;
  if(['sun.nio.ch.EPoll','sun.nio.ch.KQueue','sun.nio.ch.Poller'].includes(c)&&(ml.includes('wait')||['poll','kevent'].includes(ml)))return true;
  if(c.endsWith('.SelectorImpl')&&ml.startsWith('select'))return true;
  if((cl.includes('libjvm')||cl==='jvm')&&(['posixsemaphore::wait','os::signal_wait','semaphore::wait'].includes(ml)||ml.includes('posixsemaphore::wait')||ml.includes('semaphore::wait')||ml.includes('parker::park')||ml.includes('platformevent::park')||ml.includes('monitor::wait')))return true;
  if((c.startsWith('sun.nio.ch.')||c.startsWith('java.net.'))&&(['receive0','accept0','poll','park','read0'].includes(ml)||ml.includes('blockingreceive')||ml.startsWith('accept')))return true;
  if(c.startsWith('org.jline.')&&(['readcharacter','readbinding','read','readline'].includes(ml)||ml.startsWith('read')))return true;
  if((cl.includes('console')||cl.includes('terminal'))&&(ml.includes('read')||ml.includes('wait')))return true;
  if((cl.includes('voicechat')||cl.includes('udp')||cl.includes('datagram'))&&(['receive','receive0','read','read0','poll'].includes(ml)||ml.includes('receive')))return true;
  if(c==='libjli.so'&&['continueinnewthread','calljavainnewthread'].includes(ml))return true;
  if(['epoll_wait','kevent','poll','ppoll','select','pselect','pthread_cond_wait','pthread_cond_timedwait','sem_wait','futex_wait','futex_wait_cancelable'].includes(ml)&&(c.startsWith('lib')||c.startsWith('linux')||c===''))return true;
  return false;
}
function rewriteThreadV3(blob){
  let tf=rawFields(blob), nodeFields=tf.filter(x=>x.f===3&&x.w===2), nodes=[];
  for(let nf of nodeFields){let fs=rawFields(nf.v),cls='',method='',times=[],refs=[];for(let f of fs){if(f.f===3&&f.w===2)cls=text(f.v);else if(f.f===4&&f.w===2)method=text(f.v);else if(f.f===8)times.push(...(f.w===2?doubles(f.v):[new DataView(f.v.buffer,f.v.byteOffset,8).getFloat64(0,true)]));else if(f.f===9)refs.push(...(f.w===2?packedVarints(f.v):[f.v]));}nodes.push({fs,cls,method,times,refs});}
  let roots=[],threadTimes=[];for(let f of tf){if(f.f===5)roots.push(...(f.w===2?packedVarints(f.v):[f.v]));else if(f.f===4)threadTimes.push(...(f.w===2?doubles(f.v):[new DataView(f.v.buffer,f.v.byteOffset,8).getFloat64(0,true)]));}
  let W=Math.max(threadTimes.length,...nodes.map(n=>n.times.length),0);for(let n of nodes)while(n.times.length<W)n.times.push(0);
  let selfv=nodes.map(n=>Array.from({length:W},(_,w)=>Math.max(0,n.times[w]-n.refs.filter(j=>j>=0&&j<nodes.length).reduce((s,j)=>s+(nodes[j].times[w]||0),0))));
  let blocked=Array(nodes.length).fill(false),seen=new Set();
  function mark(i,on=false){if(!(i>=0&&i<nodes.length))return;let key=i+'|'+(on?1:0);if(seen.has(key))return;seen.add(key);let now=on||sleepingV3(nodes[i].cls,nodes[i].method);if(now)blocked[i]=true;for(let j of nodes[i].refs)mark(j,now)}
  for(let r of roots)mark(r,false);
  let removed=0;for(let i=0;i<nodes.length;i++)if(blocked[i]){removed+=sum(selfv[i]);selfv[i]=Array(W).fill(0)}
  let memo=new Map(),visiting=new Set();function inc(i){if(memo.has(i))return memo.get(i);if(visiting.has(i))return Array(W).fill(0);visiting.add(i);let v=selfv[i].slice();for(let j of nodes[i].refs)if(j>=0&&j<nodes.length){let q=inc(j);for(let w=0;w<W;w++)v[w]+=q[w]}visiting.delete(i);memo.set(i,v);return v}for(let r of roots)inc(r);
  let keep=[];for(let i=0;i<nodes.length;i++)if((memo.get(i)||Array(W).fill(0)).some(x=>x>1e-12))keep.push(i);let remap=new Map(keep.map((old,nu)=>[old,nu])),newNodeBlobs=[];
  for(let old of keep){let vals=memo.get(old)||Array(W).fill(0),childRefs=nodes[old].refs.filter(j=>remap.has(j)).map(j=>remap.get(j)),out=[],wt=false,wr=false;for(let q of nodes[old].fs){if(q.f===8){if(!wt){out.push({f:8,w:2,v:packDoubles(vals)});wt=true}}else if(q.f===9){if(!wr&&childRefs.length){out.push({f:9,w:2,v:packVars(childRefs)});wr=true}}else out.push(q)}if(!wt)out.push({f:8,w:2,v:packDoubles(vals)});if(childRefs.length&&!wr)out.push({f:9,w:2,v:packVars(childRefs)});newNodeBlobs.push(encodeFields(out))}
  let newRoots=roots.filter(r=>remap.has(r)).map(r=>remap.get(r)),newThread=Array(W).fill(0);for(let r of roots){let q=memo.get(r);if(q)for(let w=0;w<W;w++)newThread[w]+=q[w]}
  let newtf=[],insN=false,insT=false,insR=false;for(let f of tf){if(f.f===3){if(!insN){for(let b of newNodeBlobs)newtf.push({f:3,w:2,v:b});insN=true}}else if(f.f===4){if(!insT){newtf.push({f:4,w:2,v:packDoubles(newThread)});insT=true}}else if(f.f===5){if(!insR&&newRoots.length){newtf.push({f:5,w:2,v:packVars(newRoots)});insR=true}}else newtf.push(f)}if(!insN)for(let b of newNodeBlobs)newtf.push({f:3,w:2,v:b});if(!insT)newtf.push({f:4,w:2,v:packDoubles(newThread)});if(newRoots.length&&!insR)newtf.push({f:5,w:2,v:packVars(newRoots)});
  return {bytes:encodeFields(newtf),removed,before:sum(threadTimes),after:sum(newThread),nodesBefore:nodes.length,nodesAfter:keep.length,empty:keep.length===0||!newRoots.length};
}
function removeSleepingFromProfile(raw){let top=rawFields(raw),meta=top.find(x=>x.f===1&&x.w===2),mode=0;if(meta)for(let x of rawFields(meta.v))if(x.f===15&&x.w===0)mode=x.v;if(mode===1)throw Error('CPU idle filtering applies only to execution profiles.');let removed=0,before=0,after=0,threads=0,droppedThreads=0,n0=0,n1=0,newTop=[];for(let x of top){if(x.f===2&&x.w===2){let r=rewriteThreadV3(x.v);removed+=r.removed;before+=r.before;after+=r.after;n0+=r.nodesBefore;n1+=r.nodesAfter;threads++;if(r.empty)droppedThreads++;else newTop.push({f:2,w:2,v:r.bytes})}else newTop.push(x)}return{bytes:encodeFields(newTop),removed,before,after,threads,droppedThreads,nodesBefore:n0,nodesAfter:n1}}


const state={raw:null,profile:null,name:'',source:'',cleaned:null,cleanResult:null,threadRows:[],attrRows:[]};
const $=s=>document.querySelector(s);
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtBytes(n){const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function fmtDuration(ms){if(ms<1000)return ms.toFixed(0)+' ms';let s=ms/1000;if(s<60)return s.toFixed(2)+' s';let h=Math.floor(s/3600),m=Math.floor(s%3600/60),r=s%60,a=[];if(h)a.push(h+'h');if(m)a.push(m+'m');a.push(r.toFixed(1)+'s');return a.join(' ')}
function profileDuration(){return state.profile?.end&&state.profile?.start?state.profile.end-state.profile.start:0}
function threadTotal(t){return t.times.length?sum(t.times):t.roots.reduce((s,r)=>s+(r>=0&&r<t.nodes.length?sum(t.nodes[r].times):0),0)}
function normalizeCode(input){let s=input.trim();if(!s)return'';try{let u=new URL(s);if(u.hostname==='spark.lucko.me'||u.hostname.endsWith('.spark.lucko.me'))return u.pathname.split('/').filter(Boolean)[0]||'';if(u.hostname==='spark-usercontent.lucko.me')return u.pathname.split('/').filter(Boolean)[0]||'';return s}catch{return s.replace(/^\/+|\/+$/g,'').split(/[?#/]/)[0]}}
function rawUrl(code){return 'https://spark-usercontent.lucko.me/'+encodeURIComponent(code)}
const CACHE_MAX_AGE=6*60*60*1000,CACHE_MAX_BYTES=250*1024*1024;
function dbOpen(){return new Promise((ok,no)=>{let r=indexedDB.open('profiler-utils-cache',1);r.onupgradeneeded=()=>r.result.createObjectStore('profiles');r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function cacheEntries(){try{let db=await dbOpen();return await new Promise((ok,no)=>{let store=db.transaction('profiles').objectStore('profiles'),r=store.openCursor(),out=[];r.onsuccess=()=>{let c=r.result;if(!c)return ok(out);out.push({key:c.key,value:c.value});c.continue()};r.onerror=()=>no(r.error)})}catch{return[]}}
async function cacheDelete(k){try{let db=await dbOpen();await new Promise((ok,no)=>{let r=db.transaction('profiles','readwrite').objectStore('profiles').delete(k);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}catch{}}
async function gzipBytes(bytes){if(typeof CompressionStream==='undefined')return null;let stream=new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function gunzipBytes(bytes){if(typeof DecompressionStream==='undefined')throw Error('This browser cannot decompress the cached profile.');let stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer())}
function cacheStoredSize(e){return e.storedSize||e.size||(e.data&&e.data.byteLength)||0}
function cacheOriginalSize(e){return e.originalSize||e.size||(e.data&&e.data.byteLength)||0}
async function cacheCleanup(){let now=Date.now(),entries=await cacheEntries();for(let e of entries)if(!e.value||!e.value.data||now-(e.value.downloadedAt||0)>CACHE_MAX_AGE)await cacheDelete(e.key);entries=(await cacheEntries()).filter(e=>e.value&&e.value.data).sort((a,b)=>(a.value.lastAccessedAt||a.value.downloadedAt||0)-(b.value.lastAccessedAt||b.value.downloadedAt||0));let total=entries.reduce((s,e)=>s+cacheStoredSize(e.value),0);for(let e of entries){if(total<=CACHE_MAX_BYTES)break;let size=cacheStoredSize(e.value);await cacheDelete(e.key);total-=size}await renderCacheStatus()}
async function cacheGet(k){try{let db=await dbOpen(),entry=await new Promise((ok,no)=>{let r=db.transaction('profiles').objectStore('profiles').get(k);r.onsuccess=()=>ok(r.result||null);r.onerror=()=>no(r.error)});if(!entry)return null;if(entry instanceof ArrayBuffer){await cacheDelete(k);return null}if(!entry.data||Date.now()-(entry.downloadedAt||0)>CACHE_MAX_AGE){await cacheDelete(k);return null}let bytes=entry.compression==='gzip'?await gunzipBytes(entry.data):new Uint8Array(entry.data);entry.lastAccessedAt=Date.now();try{let db2=await dbOpen();await new Promise((ok,no)=>{let r=db2.transaction('profiles','readwrite').objectStore('profiles').put(entry,k);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}catch{}return bytes}catch{await cacheDelete(k);return null}}
async function cachePut(k,b){try{let raw=b instanceof Uint8Array?b:new Uint8Array(b),meta={};try{let pp=parse(raw);meta.profileType=pp.mode===1?'Allocation':'Execution';meta.durationMs=pp.end&&pp.start?pp.end-pp.start:0}catch{}let compressed=await gzipBytes(raw),useGzip=compressed&&compressed.byteLength<raw.byteLength,data=useGzip?compressed:raw,now=Date.now(),entry={data:data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),downloadedAt:now,lastAccessedAt:now,originalSize:raw.byteLength,storedSize:data.byteLength,compression:useGzip?'gzip':'none',...meta};let db=await dbOpen();await new Promise((ok,no)=>{let r=db.transaction('profiles','readwrite').objectStore('profiles').put(entry,k);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)});await cacheCleanup();return entry}catch{return null}}
async function cacheClear(){try{let db=await dbOpen();await new Promise((ok,no)=>{let r=db.transaction('profiles','readwrite').objectStore('profiles').clear();r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}catch{}await renderCacheStatus()}

function relativeAge(ms){let s=Math.max(0,Math.floor(ms/1000));if(s<60)return s+'s ago';let m=Math.floor(s/60);if(m<60)return m+'m ago';let h=Math.floor(m/60);if(h<24)return h+'h '+(m%60)+'m ago';return Math.floor(h/24)+'d ago'}
function expiresIn(downloadedAt){let left=Math.max(0,CACHE_MAX_AGE-(Date.now()-(downloadedAt||0))),m=Math.ceil(left/60000);if(m<60)return m+'m';let h=Math.floor(m/60),r=m%60;return h+'h'+(r?' '+r+'m':'')}
async function renderCacheManager(){let now=Date.now(),entries=(await cacheEntries()).filter(e=>e.value&&e.value.data&&now-(e.value.downloadedAt||0)<=CACHE_MAX_AGE).sort((a,b)=>(b.value.lastAccessedAt||b.value.downloadedAt||0)-(a.value.lastAccessedAt||a.value.downloadedAt||0)),stored=entries.reduce((s,e)=>s+cacheStoredSize(e.value),0),original=entries.reduce((s,e)=>s+cacheOriginalSize(e.value),0),saved=original?100*(1-stored/original):0;$('#cacheManagerSummary').textContent=entries.length+' profile'+(entries.length===1?'':'s')+' · '+fmtBytes(stored)+' / '+fmtBytes(CACHE_MAX_BYTES)+(original>stored?' · '+saved.toFixed(1)+'% saved':'');let list=$('#cacheList');if(!entries.length){list.innerHTML='<p class="muted">No cached Spark profiles.</p>';return}list.innerHTML=entries.map(e=>{let v=e.value,type=v.profileType||'Spark profile',duration=v.durationMs?' · '+fmtDuration(v.durationMs):'',ratio=cacheOriginalSize(v)>cacheStoredSize(v)?' · '+(100*(1-cacheStoredSize(v)/cacheOriginalSize(v))).toFixed(1)+'% saved':'';return '<article class="cache-item"><div class="cache-item-main"><a class="cache-id" href="https://spark.lucko.me/'+encodeURIComponent(e.key)+'" target="_blank" rel="noopener">'+esc(e.key)+'</a><div class="cache-meta">'+esc(type+duration)+'</div><div class="cache-meta">'+esc(fmtBytes(cacheStoredSize(v))+' stored · '+fmtBytes(cacheOriginalSize(v))+' original'+ratio)+'</div><div class="cache-meta">Last used '+esc(relativeAge(now-(v.lastAccessedAt||v.downloadedAt||now)))+' · expires in '+esc(expiresIn(v.downloadedAt))+'</div></div><div class="cache-item-actions"><button type="button" data-cache-load="'+esc(e.key)+'">Load</button><button type="button" data-cache-delete="'+esc(e.key)+'">Delete</button></div></article>'}).join('');list.querySelectorAll('[data-cache-load]').forEach(b=>b.onclick=async()=>{let code=b.dataset.cacheLoad;b.disabled=true;$('#loadStatus').textContent='Loading '+code+' from cache…';let raw=await cacheGet(code);if(raw){await loadBytes(raw,code+'.sparkprofile','Cached Spark report · https://spark.lucko.me/'+code);$('#sparkUrl').value='https://spark.lucko.me/'+code;$('#loadStatus').textContent='Loaded from compressed cache.';await renderCacheManager();await renderCacheStatus()}else{$('#loadStatus').textContent='Cached profile expired or could not be read.';await renderCacheManager()}});list.querySelectorAll('[data-cache-delete]').forEach(b=>b.onclick=async()=>{await cacheDelete(b.dataset.cacheDelete);await renderCacheManager();await renderCacheStatus()})}

async function renderCacheStatus(){let entries=await cacheEntries(),now=Date.now(),valid=entries.filter(e=>e.value&&e.value.data&&now-(e.value.downloadedAt||0)<=CACHE_MAX_AGE),stored=valid.reduce((s,e)=>s+cacheStoredSize(e.value),0),original=valid.reduce((s,e)=>s+cacheOriginalSize(e.value),0),saved=original>0?(1-stored/original)*100:0,el=$('#cacheStatus');if(el)el.textContent=valid.length+' cached profile'+(valid.length===1?'':'s')+' · '+fmtBytes(stored)+' stored'+(original>stored?' from '+fmtBytes(original)+' · '+saved.toFixed(1)+'% saved':'')+' · expires after 6 hours'}

async function loadBytes(raw,name,source){state.raw=raw;state.profile=parse(raw);state.name=name;state.source=source;state.cleaned=null;state.cleanResult=null;$('#workspace').hidden=false;$('#loadError').textContent='';renderHeader();renderOverview();renderThreads();renderAttribution();renderCleaner();selectTab('overview')}
async function loadSpark(){let code=normalizeCode($('#sparkUrl').value);if(!code)return;$('#loadStatus').textContent='Loading…';$('#loadError').textContent='';try{let cached=await cacheGet(code),raw;if(cached){raw=cached;$('#loadStatus').textContent='Loaded from compressed cache.'}else{let r=await fetch(rawUrl(code));if(!r.ok)throw Error('Spark download failed: HTTP '+r.status);raw=new Uint8Array(await r.arrayBuffer());$('#loadStatus').textContent='Downloaded. Compressing cache copy…';let entry=await cachePut(code,raw);$('#loadStatus').textContent=entry&&entry.compression==='gzip'?'Downloaded and cached: '+fmtBytes(entry.originalSize)+' → '+fmtBytes(entry.storedSize)+'.':'Downloaded and cached for up to 6 hours.'}await loadBytes(raw,code+'.sparkprofile','https://spark.lucko.me/'+code)}catch(e){$('#loadError').textContent=e.message||String(e);$('#loadStatus').textContent=''}}
function renderHeader(){let p=state.profile,d=profileDuration();$('#loaded').innerHTML=`<strong>${esc(state.name)}</strong><span>${p.mode===1?'Allocation':'Execution'} · ${fmtDuration(d)} · ${p.threads.length} threads · ${fmtBytes(state.raw.length)}</span>${state.source?`<small>${esc(state.source)}</small>`:''}`;$('#cleanTab').disabled=p.mode===1}
function cards(items){return '<div class="stats">'+items.map(([a,b])=>`<div class="stat"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')+'</div>'}
function pad(s,n,right=false){s=String(s);return right?s.padEnd(n):s.padStart(n)}
function textTable(headers,rows){let widths=headers.map((h,i)=>Math.max(String(h).length,...rows.map(r=>String(r[i]??'').length))),line=r=>r.map((v,i)=>pad(v,widths[i],i===0)).join('  ');return [line(headers),line(widths.map(w=>'─'.repeat(w))),...rows.map(line)].join('\n')}
function ansiBlock(title,headers,rows,summary=[]){const ESC=String.fromCharCode(27)+'[';let out=ESC+'1;36m'+title+ESC+'0m\n'+ESC+'2m'+textTable(headers,rows)+ESC+'0m';if(summary.length)out+='\n\n'+ESC+'1;33mSummary'+ESC+'0m\n'+summary.map(([k,v])=>ESC+'2m'+k+':'+ESC+'0m '+v).join('\n');return '```ansi\n'+out+'\n```'}
async function copyText(value,button){try{await navigator.clipboard.writeText(value)}catch{let t=document.createElement('textarea');t.value=value;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();document.execCommand('copy');t.remove()}let old=button.textContent;button.textContent='Copied';setTimeout(()=>button.textContent=old,1200)}
function threadCopy(ansi=false){let p=state.profile,d=profileDuration(),rows=state.threadRows;if(p.mode===1){let total=p.threads.reduce((s,t)=>s+threadTotal(t),0),shown=rows.reduce((s,x)=>s+x.v,0),sec=d/1000,body=rows.map(x=>[x.name,x.p.toFixed(2)+'%',rate(x.v/sec)+' · '+fmtBytes(x.v)]),summary=[['Profiler duration',fmtDuration(d)],['Entries shown',String(rows.length)],['Shown allocation',fmtBytes(shown)+' ('+(total?100*shown/total:0).toFixed(2)+'%)'],['Shown allocation rate',rate(shown/sec)],['Total allocation',fmtBytes(total)],['Total allocation rate',rate(total/sec)]];return ansi?ansiBlock('Spark Allocation Threads',['Thread','Alloc %','Rate · Total'],body,summary):textTable(['Thread','Alloc %','Rate · Total'],body)+'\n\n'+summary.map(x=>x.join(': ')).join('\n')}let total=p.threads.reduce((s,t)=>s+threadTotal(t),0),shown=rows.reduce((s,x)=>s+x.v,0),body=rows.map(x=>[x.name,x.p.toFixed(2)+'%',fmtDuration(x.v)]),summary=[['Profiler duration',fmtDuration(d)],['Threads shown',String(rows.length)],['Shown CPU',(100*shown/d).toFixed(2)+'%'],['Shown equivalent cores',(shown/d).toFixed(2)],['Total CPU',(100*total/d).toFixed(2)+'%'],['Equivalent cores',(total/d).toFixed(2)]];return ansi?ansiBlock('Spark CPU Threads',['Thread','CPU %','Time'],body,summary):textTable(['Thread','CPU %','Time'],body)+'\n\n'+summary.map(x=>x.join(': ')).join('\n')}
function attrCopy(ansi=false){let p=state.profile,d=profileDuration(),rows=state.attrRows,filter=$('#threadFilter').value.trim(),headers,body;if(p.mode===1){let a=analyze(p,filter),sec=d/1000;headers=['Plugin','Alloc rate','Thread %'];body=rows.map(x=>[x.name,rate(x.v/sec),(100*x.v/a.totalSelf).toFixed(2)+'%'])}else{let hasTicks=Number.isFinite(p.ticks)&&p.ticks>0;headers=hasTicks?['Plugin','MSPT','CPU usage']:['Plugin','CPU usage'];body=rows.map(x=>hasTicks?[x.name,(x.v/p.ticks).toFixed(3),(100*x.v/d).toFixed(2)+'%']:[x.name,(100*x.v/d).toFixed(2)+'%'])}let title=p.mode===1?'Spark Plugin Allocations':'Spark Plugin CPU Attribution';return ansi?ansiBlock(title,headers,body):textTable(headers,body)}
function renderOverview(){let p=state.profile,d=profileDuration(),tot=p.threads.reduce((s,t)=>s+threadTotal(t),0),items=[['Profile',p.mode===1?'Allocation':'Execution'],['Duration',fmtDuration(d)],['Threads',String(p.threads.length)],['File size',fmtBytes(state.raw.length)]];if(p.mode===1&&d)items.push(['Allocation rate',rate(tot/(d/1000))],['Total allocation',fmtBytes(tot)]);else if(d)items.push(['Sampled CPU',(100*tot/d).toFixed(2)+'%'],['Equivalent cores',(tot/d).toFixed(2)]);$('#overview').innerHTML=cards(items)}
function renderThreads(){let p=state.profile,d=profileDuration(),th=Math.max(0,Number($('#threadThreshold').value)||0),raw=p.threads.map(t=>({name:t.name||'(unnamed)',v:threadTotal(t)})).filter(x=>x.v>0),rows;if(p.mode===1){let total=raw.reduce((s,x)=>s+x.v,0),sec=d/1000;rows=raw.map(x=>({...x,p:100*x.v/total})).filter(x=>x.p>=th).sort((a,b)=>b.p-a.p);let shown=rows.reduce((s,x)=>s+x.v,0);state.threadRows=rows;$('#threadsOut').innerHTML=table(['Thread','Alloc %','Rate · Total'],rows.map(x=>[x.name,x.p.toFixed(2)+'%',rate(x.v/sec)+' · '+fmtBytes(x.v)]))+cards([['Entries found',String(raw.length)],['Shown',String(rows.length)],['Shown allocation',fmtBytes(shown)+' ('+(total?100*shown/total:0).toFixed(2)+'%)'],['Shown rate',rate(shown/sec)],['Total allocation',fmtBytes(total)],['Total rate',rate(total/sec)]])}else{rows=raw.map(x=>({...x,p:100*x.v/d})).filter(x=>x.p>=th).sort((a,b)=>b.p-a.p);let total=raw.reduce((s,x)=>s+x.v,0),shown=rows.reduce((s,x)=>s+x.v,0);state.threadRows=rows;$('#threadsOut').innerHTML=table(['Thread','CPU %','Time'],rows.map(x=>[x.name,x.p.toFixed(2)+'%',fmtDuration(x.v)]))+cards([['Threads found',String(raw.length)],['Shown',String(rows.length)],['Shown CPU',(100*shown/d).toFixed(2)+'%'],['Shown cores',(shown/d).toFixed(2)],['Total CPU',(100*total/d).toFixed(2)+'%'],['Equivalent cores',(total/d).toFixed(2)]])}}
function renderAttribution(){let p=state.profile,filter=$('#threadFilter').value.trim(),a=analyze(p,filter),d=profileDuration(),rows=Object.entries(a.caused).map(([id,v])=>({name:p.names[id]||id,v})).sort((x,y)=>y.v-x.v);state.attrRows=rows;if(p.mode===1){let sec=d/1000;$('#attrOut').innerHTML=table(['Plugin','Alloc rate','Thread %'],rows.map(x=>[x.name,rate(x.v/sec),(100*x.v/a.totalSelf).toFixed(2)+'%']))}else{let hasTicks=Number.isFinite(p.ticks)&&p.ticks>0;$('#attrOut').innerHTML=hasTicks?table(['Plugin','MSPT','CPU usage'],rows.map(x=>[x.name,(x.v/p.ticks).toFixed(3),(100*x.v/d).toFixed(2)+'%'])):table(['Plugin','CPU usage'],rows.map(x=>[x.name,(100*x.v/d).toFixed(2)+'%']))}}
function renderCleaner(){if(state.profile.mode===1){$('#cleanOut').innerHTML='<p class="muted">CPU cleaning is only available for execution profiles.</p>';return}if(!state.cleanResult){$('#cleanOut').innerHTML='<p class="muted">Remove identifiable idle/blocking samples while preserving the original wall-clock duration and remaining timeline data.</p>';$('#downloadClean').disabled=true;return}let r=state.cleanResult,saved=state.raw.length-r.bytes.length,sp=100*saved/state.raw.length,pct=r.before?100*r.removed/r.before:0;$('#cleanOut').innerHTML=cards([['Idle/blocking removed',(r.removed/1000).toFixed(3)+' s ('+pct.toFixed(2)+'%)'],['Active sampled time',(r.after/1000).toFixed(3)+' s'],['Nodes pruned',(r.nodesBefore-r.nodesAfter)+' / '+r.nodesBefore],['Empty threads dropped',String(r.droppedThreads)],['Original size',fmtBytes(state.raw.length)],['Cleaned size',fmtBytes(r.bytes.length)+' ('+sp.toFixed(1)+'% smaller)']]);$('#downloadClean').disabled=false}
function table(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>'<tr>'+r.map(x=>`<td>${esc(x)}</td>`).join('')+'</tr>').join(''):`<tr><td colspan="${headers.length}">No matching entries.</td></tr>`}</tbody></table></div>`}
function selectTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.pane').forEach(x=>x.hidden=x.id!==id)}
$('#loadSpark').onclick=loadSpark;$('#sparkUrl').onkeydown=e=>{if(e.key==='Enter')loadSpark()};$('#chooseFile').onclick=()=>$('#file').click();$('#file').onchange=async()=>{let f=$('#file').files[0];if(f)await loadBytes(new Uint8Array(await f.arrayBuffer()),f.name,'Local upload')};$('#drop').ondragover=e=>{e.preventDefault();$('#drop').classList.add('drag')};$('#drop').ondragleave=()=>$('#drop').classList.remove('drag');$('#drop').ondrop=async e=>{e.preventDefault();$('#drop').classList.remove('drag');let f=e.dataTransfer.files[0];if(f)await loadBytes(new Uint8Array(await f.arrayBuffer()),f.name,'Local upload')};document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>!x.disabled&&selectTab(x.dataset.tab));$('#threadThreshold').oninput=renderThreads;$('#threadFilter').oninput=renderAttribution;$('#runClean').onclick=()=>{try{state.cleanResult=removeSleepingFromProfile(state.raw);state.cleaned=state.cleanResult.bytes;renderCleaner()}catch(e){$('#cleanOut').innerHTML='<p class="error">'+esc(e.message||e)+'</p>'}};$('#downloadClean').onclick=()=>{if(!state.cleaned)return;let a=document.createElement('a'),url=URL.createObjectURL(new Blob([state.cleaned],{type:'application/octet-stream'}));a.href=url;a.download=state.name.replace(/\.sparkprofile$/i,'')+'-cpu-only.sparkprofile';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

$('#copyThreads').onclick=e=>copyText(threadCopy(false),e.currentTarget);$('#copyThreadsAnsi').onclick=e=>copyText(threadCopy(true),e.currentTarget);$('#copyAttr').onclick=e=>copyText(attrCopy(false),e.currentTarget);$('#copyAttrAnsi').onclick=e=>copyText(attrCopy(true),e.currentTarget);
$('#viewCache').onclick=async()=>{$('#cacheManager').hidden=false;await renderCacheManager();$('#cacheManager').scrollIntoView({behavior:'smooth',block:'nearest'})};$('#closeCache').onclick=()=>$('#cacheManager').hidden=true;$('#clearCache').onclick=async()=>{await cacheClear();if(!$('#cacheManager').hidden)await renderCacheManager();$('#loadStatus').textContent='Cache cleared.'};cacheCleanup();
